name: UpdateReadme CI

on:
  workflow_dispatch:
  schedule:
   # 每天北京时间23点跑(UTC+8)
     - cron:  '0 15 * * *'

jobs:
  UpdateReadme:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'oracle'
          java-version: 17
          
      - name: Run Java Version
        run: 
          echo Update README Start!!!
          java --version
          
