name: UpdateReadme CI

on:
  workflow_dispatch:
  schedule:
   # 每天北京时间23点跑(UTC+8)
     - cron:  '0 15 * * *'

jobs:
  UpdateReadme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@master
    
      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'oracle'
          java-version: 17
          
      - name: Run Java Version
        run: |
          echo Update README Start!!!
          java --version
          pwd
          ls -al
          echo ${{ github.workspace }}
          ls -al ${{ github.workspace }}
          ls -l /home/runner/work/Notepad

      - name: Commit files 
        id: commit-files
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add README.md
            git commit -m "docs: update blog"
          else
            echo "No changes detected"
          fi
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.commit-files.outputs.hasChange == 'true' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

          
