name: UpdateReadme CI

on:
  workflow_dispatch:
  schedule:
   # 每天北京时间23点跑(UTC+8)
     - cron:  '0 15 * * *'

jobs:
  UpdateReadme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@master
        with:
          fetch-depth: 0
    
      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'oracle'
          java-version: 21
          
      - name: Get Java Version
        run: |
          echo Update README Start!!!
          java --version

      - name: Run UpdateReadme.jar
        run: java -jar UpdateReadme.jar

      - name: Commit And Push README.md
        run: |
          if [ -n "$(git status --porcelain README.md)" ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add README.md
            git commit -m "Auto Update README.md"
            git push
          else
            echo "No changes detected"
          fi
