name: UpdateReadme CI

on:
  workflow_dispatch:
  schedule:
   # 每天北京时间23点跑(UTC+8)
     - cron:  '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    # Set up 
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'oracle'
          java-version: 17

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          java --version
