name: UpdateReadme CI

on:
  workflow_dispatch:
  schedule:
   # 每天北京时间23点跑(UTC+8)
     - cron:  '0 15 * * *'

jobs:
  UpdateReadme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out notepad
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Check out tools
        uses: actions/checkout@master
        with:
          ref: tools
          path: tools

      - name: Check out develop
        uses: actions/checkout@master
        with:
          ref: develop
          path: develop
    
      - name: Setup Java JDK
        uses: actions/setup-java@master
        with:
          distribution: 'oracle'
          java-version: 21
          
      - name: Prepare
        run: |
          echo Update README Start!!!
          git config user.name github-actions
          git config user.email github-actions@github.com
          cp tools/files/* .
          fileName=`cat NotepadFileName`
          cd develop
          cp $fileName ..
          
      - name: Run UpdateReadme.jar
        run: |
          java -jar UpdateReadme.jar

      - name: Commit And Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md DailyNoteSum.png DailyNoteSum
          git commit -m "Auto Update README.md"
          git push
